### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by redDwarf03**

### CODE REVIEW

**Comment by 0xVesion** [comment]
Hi @redDwarf03,
Thank you for opening this PR. I'll gladly accept the dependencies version bump and related changes, but the linting changes are unnecessary and up to personal preference. I'd instead leave the linting as is. If you make the necessary changes to your PR, I'll merge it.

**Comment by redDwarf03** [comment]
ok done. i hope it will be ok for you

**Comment by 0xVesion** [comment]
LGTM! Thank you :)

**Comment by redDwarf03** [comment]
Could you update pub.dev please 🙏

**Pull request merged**
